<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Encuestas" nsURI="http://www.example.org/encuestas" nsPrefix="Encuentas">
  <eClassifiers xsi:type="ecore:EClass" name="Encuesta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modulos" lowerBound="1"
        upperBound="-1" eType="#//Modulo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navegacion" lowerBound="1"
        upperBound="-1" eType="#//Navegacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modulo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preguntas" lowerBound="1"
        upperBound="-1" eType="#//Pregunta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pregunta" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enunciado" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respuestasUsuario" upperBound="-1"
        eType="#//RespuestaUsuario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esPrimera" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unica" eSuperTypes="#//Pregunta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opciones" lowerBound="1"
        upperBound="-1" eType="#//OpcionRespuesta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiple" eSuperTypes="#//Pregunta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="opciones" lowerBound="2"
        upperBound="-1" eType="#//OpcionRespuesta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Abierta" eSuperTypes="#//Pregunta"/>
  <eClassifiers xsi:type="ecore:EClass" name="Navegacion" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntreModulo" eSuperTypes="#//Navegacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hacia" lowerBound="1" eType="#//Modulo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="desde" lowerBound="1" eType="#//OpcionRespuesta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntrePregunta" eSuperTypes="#//Navegacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="desde" lowerBound="1" eType="#//OpcionRespuesta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hacia" lowerBound="1" eType="#//Pregunta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RespuestaUsuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpcionRespuesta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="finEncuesta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntrePreguntaDirecto" eSuperTypes="#//Navegacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="desde" lowerBound="1" eType="#//Pregunta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hacia" lowerBound="1" eType="#//Pregunta"/>
  </eClassifiers>
</ecore:EPackage>
